<?php


/*REGISTRO DE LA TABLA USER*/
//INSERT INTO USER(NAME,USER,PASSWORD,DATE_CREATION,ROL,STATUS)  VALUES('JUAN PEREZ','PEREZ','22988523',NOW(),'1',0)


/*REGISTRO DE LA TABLA CLIENT*/ 
//INSERT INTO CLIENT(NAME,CL_ID_USER,FIRST_NAME,CI,EXP,DATE_CREATION,STATUS)  VALUES('JOSE',3,'PERALES','12345678','LPZ',NOW(),0)
//INSERT INTO CLIENT(NAME,CL_ID_USER,FIRST_NAME,CI,EXP,DATE_CREATION,STATUS)  VALUES('JUANJO',3,'FLOREZ','87654321','LPZ',NOW(),0)



/* CONSULTA DE INNER JOIN*/
/*
SELECT USER.NAME,CLIENT.CL_ID_USER, CLIENT.NAME, CLIENT.FIRST_NAME,CLIENT.CI,CLIENT.EXP
FROM USER
INNER JOIN CLIENT
ON USER.ID_USER = CLIENT.CL_ID_USER;*/
?>

