<?php


/*REGISTRO DE LA TABLA USER*/
//INSERT INTO USER(US_NAME_VC,US_USER_VC,US_PASSWORD_VC,US_DATE_CREATION_DT,US_ROL_BT,US_STATUS_BT)  VALUES('JUAN PEREZ','PEREZ','22988523',NOW(),'1',0)


/*REGISTRO DE LA TABLA CLIENT*/ 
//INSERT INTO CLIENT(CL_US_ID_BI,CL_NAME_VC,CL_FIRST_NAME_VC,CL_CI_VC,CL_EXP_VC,CL_DATE_CREATION_DT,CL_STATUS_BT)  VALUES(1,'JOSE','PERALES','12345678','LPZ',NOW(),0)
//INSERT INTO CLIENT(CL_US_ID_BI,CL_NAME_VC,CL_FIRST_NAME_VC,CL_CI_VC,CL_EXP_VC,CL_DATE_CREATION_DT,CL_STATUS_BT)  VALUES(1,'JUANJO','FLOREZ','87654321','LPZ',NOW(),0)



/* CONSULTA DE INNER JOIN*/
/*
SELECT USER.US_NAME_VC,CLIENT.CL_ID_BI, CLIENT.CL_NAME_VC, CLIENT.CL_FIRST_NAME_VC,CLIENT.CL_CI_VC,CLIENT.CL_EXP_VC
FROM USER
INNER JOIN CLIENT
ON USER.US_ID_BI = CLIENT.CL_US_ID_BI;*/
?>

